# Learner component for AlphaZero-style training
from __future__ import annotations

import json
import os
import random
from typing import List

import torch
import torch.nn.functional as F
from torch_geometric.data import Batch
from torch.utils.tensorboard import SummaryWriter

from .net import ActorCritic


class AlphaZeroLearner:
    """Learner that trains on trajectories generated by actors."""

    def __init__(self, controller, recorder, counter, logger, config,
                 replay_dir: str = None, models_dir: str = None, 
                 device: torch.device | None = None, batch_size: int = 32):
        self.controller = controller
        self.recorder = recorder
        self.counter = counter
        self.logger = logger
        self.config = config

        # Use provided directories or fallback to default
        self.replay_dir = replay_dir if replay_dir else "replay_buffer"
        self.batch_size = batch_size
        
        # Policy path should be in models directory, not replay buffer
        if models_dir:
            self.policy_path = os.path.join(models_dir, "policy_latest.pt")
        else:
            self.policy_path = os.path.join(self.replay_dir, "policy_latest.pt")
            
        os.makedirs(os.path.dirname(self.policy_path), exist_ok=True)
        os.makedirs(self.replay_dir, exist_ok=True)

        # Respect training.use_cuda and use spawn-safe init
        use_cuda_cfg = getattr(getattr(config, 'training', {}), 'use_cuda', True)
        if device is not None:
            self.device = device
        else:
            self.device = torch.device("cuda" if (use_cuda_cfg and torch.cuda.is_available()) else "cpu")
        # Ensure architectural hyperparameters match the actor/worker for consistency
        embedding_dim = getattr(config.nn, 'embedding_dim', 96)
        n_heads = getattr(config.nn, 'n_heads', 6)
        n_layers = getattr(config.nn, 'transformer_layers', 2)
        gnn_layers = getattr(config.nn, 'num_gnn_layers', 3)
        dropout = getattr(config.nn, 'dropout_prob', 0.1)
        self.model_config = {
            'p_net_num_nodes': config.simulation.p_net_setting_num_nodes,
            'p_net_feature_dim': config.simulation.p_net_setting_num_node_resource_attrs,
            'v_net_feature_dim': config.simulation.v_sim_setting_num_node_resource_attrs,
            'p_net_edge_dim': config.simulation.p_net_setting_num_link_resource_attrs,
            'embedding_dim': embedding_dim,
            'n_heads': n_heads,
            'n_layers': n_layers,
            'gnn_layers': gnn_layers,
            'dropout': dropout,
            'allow_rejection': getattr(getattr(config, 'solver', {}), 'allow_rejection', False),
            'max_seq_len': getattr(config.nn, 'max_seq_len', 15),
        }
        self.policy = ActorCritic(**self.model_config).to(self.device)
        
        # Load pretrained weights if specified
        model_loaded = False
        alphazero_model_path = getattr(config.training, 'alphazero_model_path', '')
        resume_training = getattr(config.training, 'resume_training', True)
        
        # Priority 1: Specific model path
        if alphazero_model_path and os.path.exists(alphazero_model_path):
            self.policy.load_state_dict(torch.load(alphazero_model_path, map_location=self.device))
            logger.info(f"Loaded AlphaZero model from: {alphazero_model_path}")
            model_loaded = True
        # Priority 2: Resume from latest policy
        elif resume_training and os.path.exists(self.policy_path):
            # Prefer full checkpoint if available
            ckpt_full = os.path.join(os.path.dirname(self.policy_path), 'policy_latest_full.pt')
            if os.path.exists(ckpt_full):
                try:
                    ckpt = torch.load(ckpt_full, map_location=self.device)
                    self.policy.load_state_dict(ckpt['model'])
                    logger.info(f"Resumed training from: {ckpt_full}")
                    model_loaded = True
                except Exception as e:
                    logger.warning(f"Failed to load full ckpt, falling back to weights-only: {e}")
            if not model_loaded:
                self.policy.load_state_dict(torch.load(self.policy_path, map_location=self.device))
                logger.info(f"Resumed training from: {self.policy_path}")
                model_loaded = True
        
        if not model_loaded:
            logger.info("Starting training from scratch (no pretrained model loaded)")
        # Instrumentation about device and CUDA
        try:
            logger.info(f"Learner device: {self.device}, cuda.is_available={torch.cuda.is_available()}")
            if self.device.type == 'cuda':
                mem_alloc = torch.cuda.memory_allocated(self.device)
                mem_res = torch.cuda.memory_reserved(self.device)
                logger.info(f"Learner CUDA memory: alloc={mem_alloc/1e6:.1f}MB reserved={mem_res/1e6:.1f}MB")
        except Exception:
            pass
            
        learning_rate = getattr(config.training, 'policy_learning_rate', 1e-4)
        self.optimizer = torch.optim.Adam(self.policy.parameters(), lr=learning_rate)
        # If we loaded a full checkpoint, restore optimizer state
        try:
            if resume_training:
                ckpt_full = os.path.join(os.path.dirname(self.policy_path), 'policy_latest_full.pt')
                if os.path.exists(ckpt_full):
                    ckpt = torch.load(ckpt_full, map_location=self.device)
                    if 'optimizer' in ckpt:
                        self.optimizer.load_state_dict(ckpt['optimizer'])
                        logger.info("Optimizer state restored from latest full checkpoint")
        except Exception as e:
            logger.warning(f"Failed to restore optimizer state: {e}")
        
        # TensorBoard logging
        from virne.utils.config import get_run_id_dir
        tb_log_dir = os.path.join(get_run_id_dir(config), "logs")
        self.writer = SummaryWriter(tb_log_dir)
        self.global_step = 0

    # ------------------------------------------------------------------
    def train_steps(self, num_steps: int) -> None:
        self.policy.train()
        save_interval = getattr(self.config.training, 'save_interval', 10)
        log_interval = getattr(self.config.training, 'log_interval', 1)
        keep_step_checkpoints = getattr(self.config.training, 'save_checkpoint_history', False)
        
        epoch_losses = {'policy': [], 'value': [], 'total': []}
        
        guaranteed_save_step = getattr(self.config.training, 'guaranteed_save_step', 50)
        throttle_ms = getattr(self.config.training, 'learner_throttle_ms', 0)
        for step in range(num_steps):
            batch = self._load_and_prepare_batch()
            if batch is None:
                self.logger.warning("Replay buffer is not large enough to start training. Skipping step.")
                break

            batch_obs, batch_policies, batch_values, batch_masks = batch

            self.optimizer.zero_grad()
            predicted_logits = self.policy.act(batch_obs)
            predicted_values = self.policy.evaluate(batch_obs).squeeze()

            # AlphaZero policy loss: -sum(π * log_softmax(logits))
            # This is equivalent to cross-entropy with soft targets
            log_probs = F.log_softmax(predicted_logits, dim=-1)

            # Optional: mask out invalid actions before computing loss
            if batch_masks is not None:
                # Zero out gradients for invalid actions
                masked_log_probs = log_probs * batch_masks
                loss_policy = -(batch_policies * masked_log_probs).sum(dim=-1).mean()
            else:
                loss_policy = -(batch_policies * log_probs).sum(dim=-1).mean()

            # AlphaZero value loss: MSE between predicted value and final reward (z)
            loss_value = F.mse_loss(predicted_values, batch_values)

            # L2 regularization
            l2_weight = getattr(self.config.training, 'l2_weight', 1e-4)
            l2_reg = sum(p.pow(2).sum() for p in self.policy.parameters())

            total_loss = loss_policy + loss_value + l2_weight * l2_reg

            total_loss.backward()

            # Calculate gradient norm for monitoring
            grad_norm = torch.nn.utils.clip_grad_norm_(self.policy.parameters(), max_norm=1.0)

            self.optimizer.step()
            self.global_step += 1
            
            # Store losses for epoch summary
            epoch_losses['policy'].append(loss_policy.item())
            epoch_losses['value'].append(loss_value.item())
            epoch_losses['total'].append(total_loss.item())

            # TensorBoard logging
            if self.global_step % log_interval == 0:
                self.writer.add_scalar('Loss/Policy', loss_policy.item(), self.global_step)
                self.writer.add_scalar('Loss/Value', loss_value.item(), self.global_step)
                self.writer.add_scalar('Loss/L2', (l2_weight * l2_reg).item(), self.global_step)
                self.writer.add_scalar('Loss/Total', total_loss.item(), self.global_step)
                self.writer.add_scalar('Training/GradNorm', grad_norm.item(), self.global_step)
                self.writer.add_scalar('Training/LearningRate', self.optimizer.param_groups[0]['lr'], self.global_step)

                # Policy accuracy definition: argmax(logits) vs argmax(MCTS π) on minibatch samples
                pred_actions = predicted_logits.argmax(dim=-1)
                target_actions = batch_policies.argmax(dim=-1)
                policy_accuracy = (pred_actions == target_actions).float().mean()
                self.writer.add_scalar('Accuracy/Policy', policy_accuracy.item(), self.global_step)
                # CUDA mem snapshot
                try:
                    if self.device.type == 'cuda':
                        mem_alloc = torch.cuda.memory_allocated(self.device)
                        mem_res = torch.cuda.memory_reserved(self.device)
                        mem_str = f" cuda_mem={mem_alloc/1e6:.1f}/{mem_res/1e6:.1f}MB"
                    else:
                        mem_str = ""
                except Exception:
                    mem_str = ""
                self.logger.info(f"Learner Step {self.global_step}: policy_acc(argmax vs π)={policy_accuracy.item():.3f} loss_p={loss_policy.item():.4f} loss_v={loss_value.item():.4f}{mem_str}")
            
            # Save model periodically (actors read model-only latest), also full checkpoint
            if (step + 1) % save_interval == 0:
                self._save_model_atomically()
                self._save_full_checkpoint()
                if keep_step_checkpoints:
                    self._save_full_checkpoint(step=self.global_step)
                avg_policy_loss = sum(epoch_losses['policy'][-save_interval:]) / min(save_interval, len(epoch_losses['policy']))
                avg_value_loss = sum(epoch_losses['value'][-save_interval:]) / min(save_interval, len(epoch_losses['value']))
                self.logger.info(f"Learner Step {self.global_step}: Policy={avg_policy_loss:.4f}, Value={avg_value_loss:.4f}")
                # Calibration on held-out mini-batch
                try:
                    cal = self._eval_calibration(n_samples=128)
                    if cal is not None:
                        self.logger.info(f"Calibration: corr={cal['corr']:.3f} MAE={cal['mae']:.3f} ECE={cal['ece']:.3f}")
                        self.writer.add_scalar('Calib/Corr', cal['corr'], self.global_step)
                        self.writer.add_scalar('Calib/MAE', cal['mae'], self.global_step)
                        self.writer.add_scalar('Calib/ECE', cal['ece'], self.global_step)
                except Exception as e:
                    self.logger.debug(f"Calibration eval failed: {e}")
            # Guaranteed early checkpoint
            if self.global_step == guaranteed_save_step:
                try:
                    self._save_full_checkpoint(step=guaranteed_save_step)
                    self._save_model_atomically()
                    if keep_step_checkpoints:
                        # Already saved with guaranteed_save_step (== global_step); no need to duplicate
                        pass
                    self.logger.info(f"Saved guaranteed checkpoint at step {guaranteed_save_step}")
                except Exception as e:
                    self.logger.warning(f"Failed to save guaranteed checkpoint: {e}")
            if throttle_ms and throttle_ms > 0:
                import time
                time.sleep(throttle_ms / 1000.0)
        
        # Always save at the end and return summary stats
        self._save_model_atomically()
        self._save_full_checkpoint()
        if keep_step_checkpoints:
            self._save_full_checkpoint(step=self.global_step)
        
        # Return average losses for epoch summary
        if epoch_losses['policy']:
            return {
                'avg_policy_loss': sum(epoch_losses['policy']) / len(epoch_losses['policy']),
                'avg_value_loss': sum(epoch_losses['value']) / len(epoch_losses['value']),
                'avg_total_loss': sum(epoch_losses['total']) / len(epoch_losses['total']),
                'num_training_steps': len(epoch_losses['policy'])
            }
        return None

    def _model_sha256(self) -> str:
        import hashlib
        h = hashlib.sha256()
        with torch.no_grad():
            for n, p in self.policy.state_dict().items():
                h.update(n.encode()); h.update(p.detach().cpu().numpy().tobytes())
        return h.hexdigest()

    def _atomic_rename(self, tmp_path: str, final_path: str):
        os.replace(tmp_path, final_path)

    def _save_model_atomically(self):
        """Save model weights only (for actors), atomically."""
        state = self.policy.state_dict()
        tmp = self.policy_path + '.tmp'
        torch.save(state, tmp)
        self._atomic_rename(tmp, self.policy_path)
        try:
            self._export_torchscript()
        except Exception as e:
            self.logger.warning(f"Failed to export TorchScript policy: {e}")

    def _save_full_checkpoint(self, step: int = None):
        """Save full checkpoint (model+optimizer+meta) with step in filename, atomically."""
        ckpt_dir = os.path.dirname(self.policy_path)
        sha = self._model_sha256()
        meta = {
            'model': self.policy.state_dict(),
            'optimizer': self.optimizer.state_dict(),
            'global_step': self.global_step,
            'sha256': sha,
        }
        if step is None:
            fname = os.path.join(ckpt_dir, 'policy_latest_full.pt')
        else:
            fname = os.path.join(ckpt_dir, f'policy_step_{int(step):05d}.pt')
        tmp = fname + '.tmp'
        torch.save(meta, tmp)
        self._atomic_rename(tmp, fname)

    def _export_torchscript(self):
        """Export a TorchScript model for C++ inference."""
        from .net import ActorCritic, ActorCriticScriptWrapper

        ts_path = os.path.join(os.path.dirname(self.policy_path), "policy_latest.ts")
        tmp = ts_path + ".tmp"

        model = ActorCritic(**self.model_config).cpu()
        model.load_state_dict(self.policy.state_dict())
        model.eval()
        wrapper = ActorCriticScriptWrapper(model)
        wrapper.eval()

        try:
            scripted = torch.jit.script(wrapper)
        except Exception:
            # Fallback: trace with nominal shapes (may fix shapes to config)
            num_nodes = self.model_config['p_net_num_nodes']
            p_feat = self.model_config['p_net_feature_dim']
            p_edge_feat = self.model_config['p_net_edge_dim']
            v_feat = self.model_config['v_net_feature_dim']
            max_seq_len = self.model_config.get('max_seq_len', 15)

            p_net_x = torch.zeros((num_nodes, p_feat), dtype=torch.float32)
            edge_index = torch.zeros((2, max(1, num_nodes - 1)), dtype=torch.long)
            edge_attr = torch.zeros((edge_index.size(1), p_edge_feat), dtype=torch.float32)
            p_batch = torch.zeros((num_nodes,), dtype=torch.long)
            selected_p_nodes = torch.zeros((0,), dtype=torch.long)
            encoder_outputs = torch.zeros((1, max_seq_len, model.actor.decoder.embedding_dim), dtype=torch.float32)
            curr_v_node_id = torch.zeros((1,), dtype=torch.long)
            vnfs_remaining = torch.zeros((1,), dtype=torch.long)
            action_mask = torch.ones((1, model.actor.decoder.num_actions), dtype=torch.bool)

            example = {
                "p_net_x": p_net_x,
                "p_net_edge_index": edge_index,
                "p_net_edge_attr": edge_attr,
                "p_net_batch": p_batch,
                "selected_p_nodes": selected_p_nodes,
                "encoder_outputs": encoder_outputs,
                "curr_v_node_id": curr_v_node_id,
                "vnfs_remaining": vnfs_remaining,
                "action_mask": action_mask,
            }
            scripted = torch.jit.trace(wrapper, example, check_trace=False)

        scripted.save(tmp)
        self._atomic_rename(tmp, ts_path)

    def _obs_to_device(self, obs: dict) -> dict:
        """Convert observation tensors from CPU to target device."""
        from torch_geometric.data import Data

        obs_device = {}
        for key, value in obs.items():
            if key == 'p_net' and isinstance(value, dict):
                # Deserialize PyG Data from dict representation
                data = Data(
                    x=torch.tensor(value['x'], dtype=torch.float32),
                    edge_index=torch.tensor(value['edge_index'], dtype=torch.long),
                    edge_attr=torch.tensor(value['edge_attr'], dtype=torch.float32) if value.get('edge_attr') is not None else None,
                )
                obs_device[key] = data.to(self.device)
            elif isinstance(value, list):
                # Convert lists back to tensors with appropriate dtypes
                if key in ('curr_v_node_id', 'vnfs_remaining'):
                    tensor = torch.tensor(value, dtype=torch.long)
                elif key == 'action_mask':
                    # action mask serialized as 0/1, cast to bool
                    tensor = torch.tensor(value, dtype=torch.bool)
                else:
                    tensor = torch.tensor(value, dtype=torch.float32)
                obs_device[key] = tensor.to(self.device)
            elif isinstance(value, torch.Tensor):
                obs_device[key] = value.to(self.device)
            else:
                obs_device[key] = value
        return obs_device

    # ------------------------------------------------------------------
    def _load_and_prepare_batch(self):
        """Load and prepare a batch of training data from replay buffer (new schema)."""
        all_files = [f for f in os.listdir(self.replay_dir) if f.endswith('.json')]
        if len(all_files) < self.batch_size:
            return None

        batch_files = random.sample(all_files, self.batch_size)
        obs_list: List[dict] = []
        batch_policies = []
        batch_values = []
        batch_masks = []

        for fname in batch_files:
            episode_path = os.path.join(self.replay_dir, fname)
            try:
                with open(episode_path, 'r') as f:
                    data = json.load(f)
            except json.JSONDecodeError:
                # Actors may still be writing this episode; skip and continue.
                self.logger.debug(f"Skipping malformed/incomplete replay episode: {episode_path}")
                continue
            except FileNotFoundError:
                # Episode can disappear due to buffer cleanup races.
                continue
            except Exception as exc:
                self.logger.debug(f"Skipping unreadable replay episode {episode_path}: {exc}")
                continue

            # Process standardized episode format
            trajectory = data.get('trajectory', [])
            final_reward = data.get('final_reward', 0.0)

            if not trajectory:
                continue

            # Sample a random timestep from the trajectory
            step = random.choice(trajectory)

            # Extract training data using new schema
            obs = step.get('observation')
            pi = step.get('pi')  # Policy distribution over num_actions
            v_root = step.get('v_root')  # Value from NN at root
            mask = step.get('mask')  # Action mask (optional)
            # model info (optional)
            model_info = data.get('model', {})

            # Use normalized final_reward (z) as the value target for AlphaZero-style training
            # value_normalization: 'raw' | 'sign' | 'tanh'
            norm_mode = getattr(self.config.training, 'value_normalization', 'tanh')
            value_scale = float(getattr(self.config.training, 'value_scale', 1000.0))
            if norm_mode == 'sign':
                target_value = 1.0 if final_reward > 0 else -1.0
            elif norm_mode == 'tanh':
                denom = value_scale if value_scale != 0.0 else 1.0
                target_value = float(torch.tanh(torch.tensor(final_reward / denom)).item())
            else:
                target_value = final_reward

            if obs is None or pi is None or v_root is None:
                continue

            # Convert obs tensors back from CPU to GPU
            obs_gpu = self._obs_to_device(obs)

            # attach model_id info to obs if useful for analysis (kept in CPU-only keys)
            obs_gpu['model_info'] = model_info
            obs_list.append(obs_gpu)
            batch_policies.append(torch.tensor(pi, dtype=torch.float32))
            batch_values.append(torch.tensor(target_value, dtype=torch.float32))
            if mask is not None:
                batch_masks.append(torch.tensor(mask, dtype=torch.float32))
            else:
                batch_masks.append(None)

        if not obs_list:
            return None

        if len(obs_list) == 1:
            batch_obs = obs_list[0]
        else:
            p_net_batch = Batch.from_data_list([o['p_net'] for o in obs_list]).to(self.device)

            # Helper to pad variable-length sequences to the max length in batch
            def pad_cat_3d(ts_list):
                # Expect tensors of shape [1, T, F]
                lengths = [t.size(1) for t in ts_list]
                T_max = max(lengths)
                out = []
                for t in ts_list:
                    if t.size(1) < T_max:
                        pad_T = T_max - t.size(1)
                        t = torch.nn.functional.pad(t, (0, 0, 0, pad_T, 0, 0))
                    out.append(t)
                return torch.cat(out, dim=0)

            hist = pad_cat_3d([o['history_features'] for o in obs_list]).to(self.device)
            enc = pad_cat_3d([o['encoder_outputs'] for o in obs_list]).to(self.device)
            # Scalars
            curr = torch.cat([o['curr_v_node_id'] for o in obs_list], dim=0).to(self.device)
            remain = torch.cat([o['vnfs_remaining'] for o in obs_list], dim=0).to(self.device)
            # Fixed-size over actions
            mask = torch.cat([o['action_mask'] for o in obs_list], dim=0).to(self.device)
            # Not used by the model paths, but keep consistent; pad variable T
            v_x = pad_cat_3d([o['v_net_x'] for o in obs_list]).to(self.device)

            batch_obs = {
                'p_net': p_net_batch,
                'history_features': hist,
                'encoder_outputs': enc,
                'curr_v_node_id': curr,
                'vnfs_remaining': remain,
                'action_mask': mask,
                'v_net_x': v_x,
            }

        policies = torch.stack(batch_policies).to(self.device)
        values = torch.stack(batch_values).to(self.device)

        # Stack masks if available (use None if any are None)
        if all(m is not None for m in batch_masks):
            masks = torch.stack(batch_masks).to(self.device)
        else:
            masks = None

        return batch_obs, policies, values, masks

    def _eval_calibration(self, n_samples: int = 128):
        """Compute correlation, MAE, and a simple ECE on a small random batch from replay."""
        import numpy as np
        all_files = [f for f in os.listdir(self.replay_dir) if f.endswith('.json')]
        if not all_files:
            return None
        files = random.sample(all_files, min(len(all_files), n_samples))
        preds = []
        targets = []
        for fname in files:
            try:
                with open(os.path.join(self.replay_dir, fname), 'r') as f:
                    data = json.load(f)
                traj = data.get('trajectory', [])
                if not traj:
                    continue
                step = random.choice(traj)
                obs = step.get('observation')
                if obs is None:
                    continue
                obs_gpu = self._obs_to_device(obs)
                with torch.no_grad():
                    pv = self.policy.evaluate(obs_gpu).squeeze().detach().cpu().item()
                # target z consistent with training normalization
                final_reward = data.get('final_reward', 0.0)
                norm_mode = getattr(self.config.training, 'value_normalization', 'tanh')
                value_scale = float(getattr(self.config.training, 'value_scale', 1000.0))
                if norm_mode == 'sign':
                    z = 1.0 if final_reward > 0 else -1.0
                elif norm_mode == 'tanh':
                    denom = value_scale if value_scale != 0.0 else 1.0
                    z = float(torch.tanh(torch.tensor(final_reward / denom)).item())
                else:
                    z = float(final_reward)
                preds.append(pv)
                targets.append(z)
            except Exception:
                continue
        if len(preds) < 5:
            return None
        preds = np.array(preds, dtype=np.float64)
        targets = np.array(targets, dtype=np.float64)
        # Pearson correlation
        pcorr = float(np.corrcoef(preds, targets)[0,1]) if preds.std() > 1e-8 and targets.std() > 1e-8 else float('nan')
        mae = float(np.mean(np.abs(preds - targets)))
        # Simple ECE: 10 bins on preds
        bins = np.linspace(preds.min(), preds.max() + 1e-8, 11)
        ece = 0.0
        total = len(preds)
        for i in range(10):
            m = (preds >= bins[i]) & (preds < bins[i+1])
            if m.sum() == 0:
                continue
            e_bin = float(np.abs(preds[m].mean() - targets[m].mean()))
            ece += (m.sum() / total) * e_bin
        return {'corr': pcorr, 'mae': mae, 'ece': float(ece)}



    # Removed: _reconstruct_state_from_components - unused method
