arrival_rate:
  distribution: poisson
  dtype: float
  lam: 0.03
  reciprocal: true
graph_attrs_setting: null
lifetime:
  distribution: exponential
  dtype: float
  scale: 500
link_attrs_setting:
- distribution: uniform
  dtype: int
  generative: true
  high: 50
  low: 0
  name: bw
  owner: link
  type: resource
node_attrs_setting:
- distribution: uniform
  dtype: int
  generative: true
  high: 20
  low: 0
  name: cpu
  owner: node
  type: resource
num_v_nets: 50
output:
  events_file_name: events.yaml
  save_dir: dataset/v_nets
  setting_file_name: v_sim_setting.yaml
  v_nets_file_name: v_net.gml
  v_nets_save_dir: v_nets
topology:
  random_prob: 0.5
  type: random
v_net_size:
  distribution: uniform
  dtype: int
  high: 10
  low: 2
