#!/usr/bin/env python3
"""
Offline learner driver for AlphaZero SFC runs.

Use this script to resume training on replay buffers that were already
generated by actors (e.g., from a k-sweep run) without launching new actors.
For each requested experiment directory we rebuild the learner stack,
override a few training hyperparameters (like max_training_steps) and let the
learner keep updating `policy_latest.pt` using the stored JSON trajectories.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Iterable, List

from omegaconf import OmegaConf

from virne.core import Controller, Counter, Logger, Recorder
from virne.solver.learning.reinforcement_learning.alpha_vne.learner import (
    AlphaZeroLearner,
)
from virne.system.base_system import BaseSystem


def parse_k_values(spec: str) -> List[int]:
    """Parse comma and range specification like '1-5,7,9' into sorted ints."""
    values: List[int] = []
    for part in spec.split(","):
        part = part.strip()
        if not part:
            continue
        if "-" in part:
            start, end = part.split("-", 1)
            values.extend(range(int(start), int(end) + 1))
        else:
            values.append(int(part))
    return sorted(dict.fromkeys(values))


def discover_run_dirs(run_root: Path, k_values: Iterable[int]) -> List[Path]:
    """Pick the latest run directory for each requested k."""
    discovered: List[Path] = []
    for k in k_values:
        prefix = f"az_k_sweep-k{k:02d}-"
        candidates = sorted(
            (d for d in run_root.iterdir() if d.is_dir() and d.name.startswith(prefix)),
            key=lambda d: d.name,
        )
        if not candidates:
            print(f"[warn] No runs found for k={k:02d} under {run_root}", file=sys.stderr)
            continue
        discovered.append(candidates[-1])
    return discovered


def run_offline_learner(
    run_dir: Path,
    steps_per_iter: int,
    max_training_steps: int,
    batch_size: int,
    min_buffer_size: int,
    max_empty_batches: int,
    sleep_when_empty: float,
) -> None:
    """Execute the learner loop on an existing run directory."""
    config_path = run_dir / "config.yaml"
    replay_dir = run_dir / "replay_buffer"
    models_dir = run_dir / "models"

    if not config_path.exists():
        raise FileNotFoundError(f"Missing config.yaml in {run_dir}")
    if not replay_dir.exists():
        raise FileNotFoundError(f"Missing replay_buffer in {run_dir}")
    if not models_dir.exists():
        raise FileNotFoundError(f"Missing models directory in {run_dir}")

    config = OmegaConf.load(config_path)
    OmegaConf.set_struct(config, False)

    training_cfg = config.training
    training_cfg.max_training_steps = max_training_steps
    training_cfg.num_train_steps_per_epoch = steps_per_iter
    training_cfg.min_buffer_size = min_buffer_size
    training_cfg.max_empty_batches = max_empty_batches

    logger = Logger(config=config)
    logger.info(f"[offline] Resuming learner for run: {run_dir.name}")

    episodes = [f for f in replay_dir.iterdir() if f.suffix == ".json"]
    if len(episodes) < min_buffer_size:
        raise RuntimeError(
            f"Not enough episodes in {replay_dir} ({len(episodes)} < {min_buffer_size})"
        )
    logger.info(
        f"[offline] {run_dir.name}: found {len(episodes)} replay files (min={min_buffer_size})"
    )

    # Rebuild dependencies the same way the spawned learner does.
    _p_net, _ = BaseSystem.load_dataset(logger, config)
    node_attrs_setting = config.v_sim_setting["node_attrs_setting"]
    link_attrs_setting = config.v_sim_setting["link_attrs_setting"]
    graph_attrs_setting = config.v_sim_setting.get("graph_attrs_setting", {})

    counter = Counter(node_attrs_setting, link_attrs_setting, graph_attrs_setting, config)
    controller = Controller(
        node_attrs_setting, link_attrs_setting, graph_attrs_setting, config
    )
    recorder = Recorder(counter, config, worker_id=9999)

    learner = AlphaZeroLearner(
        controller,
        recorder,
        counter,
        logger,
        config,
        replay_dir=str(replay_dir),
        models_dir=str(models_dir),
        batch_size=batch_size,
    )

    total_steps = 0
    while total_steps < max_training_steps:
        stats = learner.train_steps(steps_per_iter)
        if not stats:
            logger.warning(
                "[offline] Learner.train_steps returned without progress; stopping early."
            )
            break

        iter_steps = int(stats.get("num_training_steps", steps_per_iter))
        total_steps += iter_steps
        logger.info(
            f"[offline] {run_dir.name}: +{iter_steps} steps "
            f"(total={total_steps}/{max_training_steps}) "
            f"avg_total_loss={stats['avg_total_loss']:.4f}"
        )

    learner.writer.flush()
    learner.writer.close()
    logger.info(
        f"[offline] Finished learner for {run_dir.name}: total_steps={total_steps}"
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Run the AlphaZero learner offline on stored replay buffers."
    )
    parser.add_argument(
        "--run-root",
        default="results/alpha_zero_sfc",
        help="Directory containing experiment run subfolders.",
    )
    parser.add_argument(
        "--run-ids",
        nargs="*",
        help="Specific run directory names to process (overrides --k-values).",
    )
    parser.add_argument(
        "--k-values",
        default="1-12",
        help="Comma/range list of k values (used to pick the latest run per k).",
    )
    parser.add_argument(
        "--steps-per-iter",
        type=int,
        default=256,
        help="Gradient steps per learner iteration (sets training.num_train_steps_per_epoch).",
    )
    parser.add_argument(
        "--max-training-steps",
        type=int,
        default=8192,
        help="Total gradient steps to run per experiment.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=32,
        help="Learner batch size when sampling replay buffer files.",
    )
    parser.add_argument(
        "--min-buffer-size",
        type=int,
        default=128,
        help="Minimum number of replay files required before training proceeds.",
    )
    parser.add_argument(
        "--max-empty-batches",
        type=int,
        default=2000,
        help="How many times the learner will wait for data before exiting.",
    )
    parser.add_argument(
        "--sleep-when-empty",
        type=float,
        default=1.0,
        help="Seconds to sleep when replay buffer lacks enough samples.",
    )
    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    run_root = Path(args.run_root).expanduser().resolve()
    if not run_root.exists():
        parser.error(f"Run root not found: {run_root}")

    if args.run_ids:
        run_dirs = [run_root / rid for rid in args.run_ids]
    else:
        k_values = parse_k_values(args.k_values)
        run_dirs = discover_run_dirs(run_root, k_values)

    if not run_dirs:
        parser.error("No run directories to process.")

    for run_dir in run_dirs:
        if not run_dir.exists():
            print(f"[warn] Skipping missing run directory: {run_dir}", file=sys.stderr)
            continue
        try:
            run_offline_learner(
                run_dir=run_dir,
                steps_per_iter=args.steps_per_iter,
                max_training_steps=args.max_training_steps,
                batch_size=args.batch_size,
                min_buffer_size=args.min_buffer_size,
                max_empty_batches=args.max_empty_batches,
                sleep_when_empty=args.sleep_when_empty,
            )
        except Exception as exc:
            print(f"[error] {run_dir.name}: {exc}", file=sys.stderr)


if __name__ == "__main__":
    main()
